#!/usr/bin/env python
"""
reddit_scraper

Scrape images from a subreddit

Usage:
  reddit_scraper initialize
  reddit_scraper scrape <subreddit>

Options:
  -h --help              Show this screen

"""
import sys

from docopt import docopt

import praw

from lib.db import init_db


CMDARGS = docopt(__doc__)
LIMIT = 10
USER_AGENT = 'Reddit Scraper Script'


def initialize():
    result = raw_input("Warning: This will drop all tables and start the "
                       "database over from scratch.  Are you sure you want to "
                       "do this?  Enter 'yes' if so...\n")
    if result != 'yes':
        print "exiting..."
        sys.exit()
    print "Initializing db..."
    init_db()


def scrape_subreddit(subreddit_name):
    reddit = praw.Reddit(user_agent=USER_AGENT)
    subreddit = reddit.get_subreddit(subreddit_name)
    for submission in subreddit.get_new(
            limit=LIMIT, params={'after': 't3_4fp33k'}):
        print submission.name


if __name__ == '__main__':
    if CMDARGS['initialize']:
        initialize()
