#!/usr/bin/env python
"""
reddit_scraper

Scrape images from a subreddit

Usage:
  reddit_scraper initialize
  reddit_scraper backfill <subreddit> <date>
  reddit_scraper scrape <subreddit>

Options:
  -h --help              Show this screen

"""
from dateutil.parser import parse

import sys

from docopt import docopt

from lib import api as scraper_api


def initialize():
    result = raw_input(
        "Warning: This will drop all tables and start the database over from "
        "scratch.  Are you sure you want to do this?  Enter 'yes' if so...\n")
    if result != 'yes':
        print "exiting..."
        sys.exit()
    print "Initializing db..."
    scraper_api.initialize_database()


def backfill(subreddit_name, date):
    try:
        date = parse(date)
    except ValueError:
        print "Bad date format"
        sys.exit(1)
    try:
        scraper_api.scrape(subreddit_name, backfill_to=date)
    except Exception as ex:
        print str(ex)
        sys.exit(1)


def scrape(subreddit_name):
    try:
        scraper_api.scrape(subreddit_name)
    except Exception as ex:
        print str(ex)
        sys.exit(1)


if __name__ == '__main__':
    CMDARGS = docopt(__doc__)
    if CMDARGS['initialize']:
        initialize()
    elif CMDARGS['scrape']:
        scrape(CMDARGS['<subreddit>'])
    elif CMDARGS['backfill']:
        backfill(CMDARGS['<subreddit>'], CMDARGS['<date>'])
