#!/usr/bin/env python
"""
reddit_scraper

Scrape images from a subreddit

Usage:
  reddit_scraper <subreddit>

Options:
  -h --help              Show this screen

"""
from docopt import docopt

import praw


USER_AGENT = 'Reddit Scraper Script'
LIMIT = 10


def main(subreddit_name):
    reddit = praw.Reddit(user_agent=USER_AGENT)
    subreddit = reddit.get_subreddit(subreddit_name)
    for submission in subreddit.get_new(
            limit=LIMIT, params={'after': 't3_4fp33k'}):
        print submission.name


if __name__ == '__main__':
    args = docopt(__doc__)
    main(args['<subreddit>'])
