#!/usr/bin/env bash


IMGUR_CLIENT_ID=''
IMGUR_CLIENT_SECRET=''

REDDIT_SCRAPER_DB_URI="${REDDIT_SCRAPER_DB_URI}_test"
REDDIT_SCRAPER_IMAGES_PATH="${REDDIT_SCRAPER_IMAGES_PATH}_test"


echo "Creating test database..."
createdb ${REDDIT_SCRAPER_DB_URI##*/}

nosetests -v $1

echo "Dropping test database..."
dropdb ${REDDIT_SCRAPER_DB_URI##*/}

echo "Removing test image directory"
rm -rf $REDDIT_SCRAPER_IMAGES_PATH
